apiVersion: v1
kind: Secret
metadata:
  name: revive-thrive-secrets
  namespace: revive-thrive
type: Opaque
stringData:
  FLASK_SECRET_KEY: "replace-me"
  BUSINESS_EMAIL: "replace-me"
  MAIL_USERNAME: "replace-me"
  MAIL_PASSWORD: "replace-me"
  TELEGRAM_BOT_TOKEN: "replace-me"
  TELEGRAM_CHAT_ID: "replace-me"
  ADMIN_USERNAME: "admin"
  ADMIN_PASSWORD: "replace-me"
